remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Dr Caren Han
email: Caren.Han@sydney.edu.au
description: |\n
··Senior Lecturer,\n
··\n
··(Associate Professor in U.S.)\n
··\n
logo: "./caren_fun.jpg"
